Issue/1336 add option to hide assets in importer
ucfopen/Materia pull request #1357
Opened 2022-01-03 20:18 UTC by emanuelGitCodes

2022-01-13 19:49 UTC, clpetersonucf requested changes
This appears to only be half of the implementation we had discussed - the asset is still always visible in the list, with the only difference being the state of the delete/deleted button. Ideally, deleted assets are not visible by default, but I don't see anything in the client-side JS to hide the deleted assets. The behavior should be more like:

If an asset is _not_ deleted: `Delete` button is enabled, asset is visible in the list by default
If an asset _is_ deleted: `Restore` button is enabled, asset is _not_ visible by default, and is only made visible when a separate "Show deleted assets" option is checked.

2022-01-13 19:49 UTC, clpetersonucf commented on fuel/app/themes/default/partials/catalog/media.php
> +						<span ng-if='file.is_deleted == 1'>DELETED</span>
Given my comments in the review generally, we should probably change the word `DELETED` to be something more directly tied to the action the button will perform in this state - `Restore` or `Undelete` seems more appropriate.

2023-03-13 17:43 UTC, FrenjaminBanklin commented
This one's also covered by #1442, I think?

2023-03-22 18:33 UTC, clpetersonucf commented
Yup, this was superseded by and replaced with #1442. Closing.

2023-03-22 18:33 UTC, closed without merging