Converts LTI views to React
ucfopen/Materia pull request #1415
Opened 2022-11-08 21:55 UTC by cayb0rg

2023-01-20 15:46 UTC, clpetersonucf requested changes
Some high level design comments:

- It looks like you're trying to re-implement `get_owners` and `request_access` in the v1 API, but those API requests actually already exist - they're just not in v1. I know, it's confusing. `post_request_access` is a method in `fuel/app/classes/controller/api/instance.php`. The API in Materia is currently not great: older API requests are in v1, and newer API requests are in their respective API controller. It's something that has to be rebuilt from the ground up in the future python rewrite. `get_owners` probably isn't even required, the ownership is assessed in the LTI preview controller, and we're better off emitting that flag to the window like other JS constants in other React views.
- Generally, try and avoid making changes to any of the old (or creating new) stylesheets in `src/css`. My goal is to kill these completely, and implement CSS in one of two places: a common stylesheet (`include.scss`) in the components directory, or a component-specific stylesheet in that same directory. With several LTI components making use of similar styles, it'd probably make sense for them all to inherit the same stylesheet.
- I noticed you made a change to the `post_login.php` partial under `themes/default/lti/partials`. That's also part of the deprecated file structure, as those views are all being removed. Anything you're changing there should be changed in the corresponding components instead. The individual React views and their components are replacing the old PHP partials.

2023-03-13 20:20 UTC, clpetersonucf commented
Updated with changes to the main react branch. Something I'm noticing: the LTI picker isn't loading any widgets, which I suspect is due to pagination in the `widget_paginate_instances_get`, but haven't looked at it in detail.

2023-03-22 14:38 UTC, clpetersonucf requested changes
The diff is looking better, I don't see any glaring issues.

The test suite is failing consistently:
```
There was 1 failure:

1) Test_Api_V1::test_widget_instance_lock_for_another_user
Failed asserting that false is true.

/var/www/html/fuel/app/tests/api/v1.php:496
```

The only other thing I'm noticing is that attempting to test LTI Assignment Launch in the test provider yields the message `LTI Assignment URL can not be blank!` even when the the assignment URL is populated.

2023-03-22 14:41 UTC, clpetersonucf commented on fuel/app/classes/materia/api/v1.php
> +	static public function request_access(string $inst_id, int $owner_id)
This API call is unnecessary, newer API endpoints are in the API controllers. `post_request_access` is in `fuel/app/classes/controller/api/instance.php`.

2023-03-22 14:57 UTC, clpetersonucf commented
> The only other thing I'm noticing is that attempting to test LTI Assignment Launch in the test provider yields the message `LTI Assignment URL can not be blank!` even when the the assignment URL is populated.

Update: this is probably because the test provider was relying on jquery for basic functionality, which is no longer bundled with Materia. We can probably update the page to use a CDN link for jQuery. I'd rather not bundle it with Materia's JS and CSS assets.

2023-03-28 21:47 UTC, FrenjaminBanklin requested changes
It looks like the LTI-relevant XML files got caught up in sweeping deletions, but those should probably be restored.

There are a few spots I noticed that could use some cleanup re: extraneous white space and removing anything left over from debugging.

The LTI test provider's behavior seems a bit unpredictable, but I haven't really been able to nail down a pattern. Buttons that should be sending requests with bad OAuth signatures appear not to be causing any problems when they probably should, for example. Since so much is being changed, this may also be a good time to add the means to make additional checks - loading a widget as an instructor who does not own it, loading a widget in guest mode, loading an unknown assignment, etc.

Also, though it's minor, it looks like the course navigation screen's appearance is different. The two columns should be taking up the same amount of vertical space, but one is taller than the other.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/modules/lti/classes/controller/lti.php
> +		{
Try to clean up any trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/modules/lti/classes/controller/lti.php
> +
Try to clean up any trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/modules/lti/classes/controller/lti.php
> +
Try to clean up any trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/tests/api/v1.php
> +}
Trailing new line is good practice.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/themes/default/lti/partials/config_xml.php
This file is still being loaded when visiting `https://site_url/lti/`.

Is this being replaced with something? If not, restore this file.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/modules/lti/classes/controller/error.php
It looks like the specific LTI error partials have been removed in favor of putting all errors through a single function and controlling what shows up on the page that way?

If so, clean up unnecessary variable usage in the relevant controllers and consider adding additional buttons to the LTI test provider to make sure all of the cases are covered.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/themes/default/lti/partials/error_autoplay_misconfigured.php
See above message re: consolidating LTI errors. Make sure there's something equivalent to this removed partial in the new code, and make sure there's a way for us to test it.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/themes/default/lti/partials/error_lti_guest_mode.php
See above message re: consolidating LTI errors. Make sure there's something equivalent to this removed partial in the new code, and make sure there's a way for us to test it.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/themes/default/lti/partials/error_unknown_assignment.php
See above message re: consolidating LTI errors. Make sure there's something equivalent to this removed partial in the new code, and make sure there's a way for us to test it.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/themes/default/lti/partials/error_unknown_user.php
See above message re: consolidating LTI errors. Make sure there's something equivalent to this removed partial in the new code, and make sure there's a way for us to test it.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on src/components/lti/select-item.jsx
> +        sectionRender =
Try to clean up trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on src/components/lti/select-item.jsx
> +        }
Try to clean up trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on src/components/lti/select-item.jsx
> +
Try to clean up trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on src/components/lti/select-item.jsx
> +        staleTime: Infinity,
Try to clean up trailing whitespace.

2023-03-28 21:47 UTC, FrenjaminBanklin commented on fuel/app/themes/default/lti/partials/outcomes_xml.php
This seems like it's still being loaded as part of the `on_score_updated_event` LTI event. Is it being replaced with something? If not, restore this file.

2023-04-11 21:30 UTC, clpetersonucf approved these changes

2023-04-11 21:32 UTC, merged